# Generated by Django 5.1 on 2024-08-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_profile_birth_date_profile_github_profile_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='projects',
            new_name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
