# Generated by Django 5.1 on 2024-08-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_remove_skill_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
    ]
